# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.provider "virtualbox" do |v|
    v.customize ["modifyvm", :id, "--memory", 256]
  end

  config.vm.define :haproxy, primary: true do |haproxy_config|

    haproxy_config.vm.hostname = 'haproxy'
    haproxy_config.vm.network :forwarded_port, guest: 8080, host: 8080
    haproxy_config.vm.network :forwarded_port, guest: 80, host: 8081

    haproxy_config.vm.network :private_network, ip: "172.28.33.10"
    haproxy_config.vm.provision :shell, :path => "haproxy-setup.sh"

  end
  config.vm.define :nodejs do |nodejs_config|

    nodejs_config.vm.hostname = 'nodejs'
    nodejs_config.vm.network :private_network, ip: "172.28.33.11"
    nodejs_config.vm.network "forwarded_port", guest: 3000, host: 3000
    nodejs_config.vm.provision :shell, :path => "nodejs-setup.sh"

  end
  config.vm.define :mongo do |mongo_config|

    mongo_config.vm.hostname = 'mongo'
    mongo_config.vm.network :private_network, ip: "172.28.33.12"
    config.vm.network "forwarded_port", guest: 27017, host: 27017
    mongo_config.vm.provision :shell, :path => "mongo-setup.sh"

  end
end
